# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_to_index <- function(x) {
    .Call(`_indexthis_cpp_to_index`, x)
}

cpp_double_factor_to_index <- function(x1, x2) {
    .Call(`_indexthis_cpp_double_factor_to_index`, x1, x2)
}

